"""Hodnoty v db mohou být null, aby se web zobrazil i bez dat, když se nebudou k dispozici.

Revision ID: 331a5d61b884
Revises: 
Create Date: 2025-03-27 14:09:23.655525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331a5d61b884'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('concert')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert',
    sa.Column('id_concert', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=True),
    sa.Column('venue', sa.VARCHAR(length=100), nullable=False),
    sa.Column('event_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_past', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id_concert')
    )
    op.create_table('news',
    sa.Column('id_news', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_news')
    )
    # ### end Alembic commands ###
